services:
  server-main:
    container_name: server-main-app
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - gamech-net
  client-main:
    container_name: client-main-app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '5174:5173'
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - gamech-net
    depends_on:
      - server-main

networks:
  gamech-net:
    driver: bridge
